EnterpriceResourcePlaning(ERP)/Controllers/JsonDataGenerateController.cs
using EnterpriceResourcePlaning_ERP_.BaseRepository;
using EnterpriceResourcePlaning_ERP_.Models;
using EnterpriceResourcePlaning_ERP_.Repository;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.Script.Serialization;



namespace EnterpriceResourcePlaning_ERP_.Controllers
{
    public class JsonDataGenerateController : Controller
    {
        string connection = WebConfigurationManager.ConnectionStrings["ErpModelEntities"].ConnectionString;

        JsonDataWriteAndRead JsonWriteAndRead = new JsonDataWriteAndRead();
        public ActionResult FirstPage()
        {

            return View();
        }

        public ActionResult GridViewPage()
        {

            return View();
        }


        // GET: JsonDataGenerate
        public ActionResult JsonfileCreate()
        {

            var ModuleList = new List<Utl_Dynamic_Module>();
            var TableList = new List<Utl_Dynamic_Table>();
            var TableColumnList = new List<Utl_Dynamic_Table_Column>();
            var autocodePropertyList = new List<Utl_Dynamic_Autocode_Property>();
            var ddPropertyList = new List<Utl_Dynamic_Dropdown_Property>();
            var filterPropertyList = new List<Utl_Dynamic_Filter_Property>();
            var validationPropertyList = new List<Utl_Dynamic_Validation_Property>();
            var tableFunList = new List<Utl_Dynamic_Table_Function>();
            SqlConnection conn = new SqlConnection(connection);



            string moduleIdquery = "SELECT [ModuleId] FROM [dbo].[Utl_Dynamic_Module]";
            SqlCommand command = new SqlCommand(moduleIdquery, conn);
            conn.Open();
            SqlDataReader modulIDReader = command.ExecuteReader();

            var ModuleIDList = new List<long>();
            while (modulIDReader.Read())
            {

                long moduleId = long.Parse(modulIDReader["ModuleId"].ToString());


                ModuleIDList.Add(moduleId);
            }
            modulIDReader.Close();

            //--------Module----------//
            foreach (var MId in ModuleIDList)
            {
                string modulequery = "SELECT [ModuleId], [ApplicationId] ,[ExistingModuleId] ,[IsNewCopy] ,[ModuleName] ,[ModuleCaption] ,[ReportTitle] "
                    + ",[IsDrilldownReport] ,[CategoryId] ,[ImagePath] ,[ModuleType] ,[SlNo] ,[IsActive] ,[DeveloperSyncId] ,[Entry_User_Id]"
                    + " ,[Entry_By] ,[Entry_Date] ,[Update_By] ,[Update_Date] ,[Check_By] ,[Check_Date] ,[Approve_By] ,[Approve_Date] ,[Delete_By] "
                    + ",[Delete_Date] ,[Is_Approved]  ,[Is_Active] ,[Is_Deleted] ,[Work_Follow_Position] ,[Row_Id] ,[Cancel_By] ,[Cancel_Date]"
                    + " ,[Is_Cancel] FROM [dbo].[Utl_Dynamic_Module] where ModuleId= '" + MId + "'";


                SqlCommand modulCmd = new SqlCommand(modulequery, conn);
                SqlDataReader modulReader = modulCmd.ExecuteReader();


                while (modulReader.Read())
                {

                    long ModuleId = long.Parse(modulReader["ModuleId"].ToString());
                    int applicationId = Convert.ToInt32(modulReader["ApplicationId"]);
                    long ExiModulId = long.Parse(modulReader["ExistingModuleId"].ToString());
                    bool isNewCopy = bool.Parse(modulReader["IsNewCopy"].ToString());

                    string moduleName = modulReader["ModuleName"].ToString();
                    string moduleCaption = modulReader["ModuleCaption"].ToString();
                    string reportTitle = modulReader["ReportTitle"].ToString();
                    bool isDrillDownReport = bool.Parse(modulReader["IsDrilldownReport"].ToString());

                    int categoryId = Convert.ToInt32(modulReader["CategoryId"]);
                    string imagePath = modulReader["ImagePath"].ToString();
                    int moduleType = Convert.ToInt32(modulReader["ModuleType"]);
                    decimal siNo = decimal.Parse(modulReader["SlNo"].ToString());

                    bool isActive = bool.Parse(modulReader["IsActive"].ToString());
                    string developerSyId = modulReader["DeveloperSyncId"].ToString();
                    string rowId = modulReader["Row_Id"].ToString();

                    long entryUserId = (modulReader["Entry_User_Id"] != DBNull.Value) ? Convert.ToInt64(modulReader["Entry_User_Id"]) : 0;

                    string entryBy = modulReader["Entry_By"].ToString();

                    DateTime? entryDate = (modulReader["Entry_Date"] == DBNull.Value) ? (DateTime?)null : Convert.ToDateTime(modulReader["Entry_Date"]);

                    string updateBy = modulReader["Update_By"].ToString();
                    DateTime? updateDate = (modulReader["Update_Date"] == DBNull.Value) ? (DateTime?)null : Convert.ToDateTime(modulReader["Update_Date"]);

                    string checkBy = modulReader["Check_By"].ToString();
                    DateTime? checkDate = (modulReader["Check_Date"] == DBNull.Value) ? (DateTime?)null : Convert.ToDateTime(modulReader["Check_Date"]);

                    string approveBy = modulReader["Approve_By"].ToString();
                    DateTime? approveDate = (modulReader["Approve_Date"] == DBNull.Value) ? (DateTime?)null : Convert.ToDateTime(modulReader["Approve_Date"]);

                    string deleteBy = modulReader["Delete_By"].ToString();
                    DateTime? deleteDate = (modulReader["Delete_Date"] == DBNull.Value) ? (DateTime?)null : Convert.ToDateTime(modulReader["Delete_Date"]);

                    string cancelBy = modulReader["Cancel_By"].ToString();
                    DateTime? cancelDate = (modulReader["Cancel_Date"] == DBNull.Value) ? (DateTime?)null : Convert.ToDateTime(modulReader["Cancel_Date"]);

                    bool isApproved = bool.Parse(modulReader["Is_Approved"].ToString());
                    bool is_Active = bool.Parse(modulReader["Is_Active"].ToString());
                    bool isDelete = bool.Parse(modulReader["Is_Deleted"].ToString());
                    bool isCandel = bool.Parse(modulReader["Is_Cancel"].ToString());
                    int workFollowPosition = Convert.ToInt32(modulReader["Work_Follow_Position"]);


                    Utl_Dynamic_Module ModulVM = new Utl_Dynamic_Module(ModuleId, applicationId, ExiModulId, isNewCopy, moduleName, moduleCaption, reportTitle, isDrillDownReport, categoryId,
                        imagePath, moduleType, siNo, isActive, developerSyId, rowId, entryUserId, entryBy, entryDate, updateBy, updateDate, checkBy, checkDate, approveBy, approveDate, deleteBy,
                        deleteDate, cancelBy, cancelDate, isApproved, is_Active, isDelete, isCandel, workFollowPosition);

                    ModuleList.Add(ModulVM);
                }
                modulReader.Close();

                //---------Table ------------//
                string Tablequery = "SELECT [TableId] ,[ModuleId], ParentModuleId, ForeignModuleId,  [ApplicationId] ,[TableCaption] ,[ModuleTableCaption],[TableName] ,[RefreshType] ,[ParentTableId] "
                + ",[ForeignTableId]  ,[IsExternalDataShow] ,[ExternalDataCaption] ,[ExternalDataFilter]  ,[ExistingTableId]  ,[ModuleWidth] ,[ModuleHeight] ,[FormWidth]"
                + " ,[PositionExp] ,[RowPosition] ,[ColPosition] ,[IsReadOnly] ,[IsWorkFollow] ,[IsAutoToggle] ,[ProcedureName] ,[ProcedureCaption] ,[ProcedureValidation]"
                + " ,[ProcFireOnTrans],[ReportProcedureName] ,[RptProcForWorksheet] ,[ProcFooterView],[ProcFooterDml] ,[ReportFileName] ,[ShowOnReport],[SqlStatement], "
                + "[ObjectType] ,[TemplateType] ,[SlNo]  ,[DeveloperSyncId] ,[Entry_User_Id] ,[Entry_By]  ,[Entry_Date] ,[Update_By] ,[Update_Date] ,[Check_By],"
                + "[Check_Date]  ,[Approve_By] ,[Approve_Date] ,[Delete_By] ,[Delete_Date] ,[Is_Approved] ,[Is_Active] ,[Is_Deleted] ,[Work_Follow_Position],[Row_Id],"
                + "[Cancel_By] ,[Cancel_Date] ,[Is_Cancel] FROM [Utl_Dynamic_Table] Where ModuleId = '" + MId + "'";


                SqlCommand tableCmd = new SqlCommand(Tablequery, conn);
                SqlDataReader tableReader = tableCmd.ExecuteReader();


                while (tableReader.Read())
                {

                    long tableId = long.Parse(tableReader["TableId"].ToString());
                    long moduleId = long.Parse(tableReader["ModuleId"].ToString());
                    long parentModuleId = (tableReader["ParentModuleId"] != DBNull.Value) ? Convert.ToInt64(tableReader["ParentModuleId"]) : 0;
                    long foreignModuleId = (tableReader["ForeignModuleId"] != DBNull.Value) ? Convert.ToInt64(tableReader["ForeignModuleId"]) : 0;

                    long applicationId = (tableReader["ApplicationId"] != DBNull.Value) ? Convert.ToInt64(tableReader["ApplicationId"]) : 0;

                    string tableCaption = tableReader["TableCaption"].ToString();
                    string moduleTblCaption = tableReader["ModuleTableCaption"].ToString();
                    string tableName = tableReader["TableName"].ToString();

                    string refreshType = tableReader["RefreshType"].ToString();

                    long parentTableId = long.Parse(tableReader["ParentTableId"].ToString());
                    long foreignTableId = long.Parse(tableReader["ForeignTableId"].ToString());

                    bool isExternalDataShow = bool.Parse(tableReader["IsExternalDataShow"].ToString());
                    string externalDataCaption = tableReader["ExternalDataCaption"].ToString();
                    string externalDataFilter = tableReader["ExternalDataFilter"].ToString();

                    long existingTableId = (tableReader["ExistingTableId"] != DBNull.Value) ? Convert.ToInt64(tableReader["ExistingTableId"]) : 0;

EnterpriceResourcePlaning(ERP)/Views/JsonDataGenerate/FirstPage - Copy.cshtml
@{
    ViewBag.Title = "FirstPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>FirstPage</h2>

@Html.ActionLink("Json File Create", "JsonfileCreate", "JsonDataGenerate",  new { @class = "btn btn-primary" })

@Html.ActionLink("Json Data Read", "JsonfileRead", "JsonDataGenerate",  new { @class = "btn btn-primary" })

EnterpriceResourcePlaning(ERP)/Views/JsonDataGenerate/FirstPage.cshtml
@{
    ViewBag.Title = "FirstPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row ml-1">
    <h3>JSON file create for individual page: </h3>

    @Html.ActionLink("Json File Create", "JsonfileCreate", "JsonDataGenerate", new { @class = "btn btn-primary" })
@*@Html.ActionLink("Json Data Read", "JsonfileRead", "JsonDataGenerate", new { @class = "btn btn-primary" })*@

</div>
<br />
<br />



<div class="row ml-1" style="width:100%">
    <div class="col-md-12">
        <h4 class="ml-2 text-center">Json file read Module base</h4>

        <div class="col-md-6">

            <input type="text" class="form-control form-control-sm " id="moduleId" name="ModuleId" placeholder="ModuleId">

            <input type="text" class="form-control form-control-sm " id="tableId" name="TableId" placeholder="TableId">

            <input type="text" class="form-control form-control-sm " id="pkId" name="PkId" placeholder="PkId">

        </div>
        <div class="col-md-6">

             <input type="text" class="form-control form-control-sm " id="fkId" name="FkId" placeholder="FkId">

            <input type="text" class="form-control form-control-sm " id="dmlType" name="DmlType" placeholder="DmlType">

            <input type="submit" value="Submit" class="form-control form-control-sm btn btn-success" onclick="formSubmit()" />
        </div>
    </div>

</div>
<br />
<br />
<div class="row ml-1 border bg-white p-2" id="QueryResult">


</div>
<br />


@*@Html.ActionLink("Json Data Read using linq", "JsonDataRead", "GetDynamicTableInfo", new { ModuleId = 185, TableId = 448, PkId = "0", FkId = "0", DmlType = "binddata_fv_update" }, new { @class = "btn btn-info" })


    <h3>Table All Data Generate to Json</h3>

    <a href="/OverAllTableData/AllDataJsonfileCreate" class="btn btn-danger">Table All Data Generate to json</a>*@

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>

    function formSubmit() {
        var ModuleId = $('#moduleId').val();
        var TableId = $('#tableId').val();
        var PkId = $('#pkId').val();
        var FkId = $('#fkId').val();
        var DmlType = $('#dmlType').val();

        var parameter = {
            moduleId: ModuleId,
            tableId: TableId,
            pkId: PkId,
            fkId: FkId,
            dmlType: DmlType
        }

        $.ajax({
            type: "POST",
            url: '@Url.Action("JsonDataRead", "GetDynamicTableInfo")',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data: JSON.stringify(parameter),
            success: function (queryString) {

                $("#QueryResult").html("<h2>" + queryString[0] + "</h2><p class='p-1'>" + queryString[1] + "</p><h2>" + queryString[2] +"</h2>");
                  
                //console.log(queryString);
                //alert(queryString);
            }
        });
    }



</script>

EnterpriceResourcePlaning(ERP)/Views/JsonDataGenerate/GridViewPage.cshtml
@{
    ViewBag.Title = "GridViewPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row ml-1">
    <form id="myForm">
        <div class="col-md-12">
            <h4 class="ml-2 text-center">Json file read Module base</h4>

            <div class="col-md-6">

                <input type="number" class="form-control form-control-sm " id="moduleId" name="ModuleId" placeholder="ModuleId">

                <input type="number" class="form-control form-control-sm " id="tableId" name="TableId" placeholder="TableId">

                <input type="text" class="form-control form-control-sm " id="fkId" name="FkId" placeholder="FkId">

                <input type="text" class="form-control form-control-sm " id="filterExpression" name="FilterExpression" placeholder="FilterExpression">

                <input type="text" class="form-control form-control-sm " id="workfollowAction" name="WorkfollowAction" placeholder="WorkfollowAction">

            </div>
            <div class="col-md-6">

                <input type="number" class="form-control form-control-sm " id="isDeleteShow" name="IsDeleteShow" placeholder="IsDeleteShow">

                <input type="number" class="form-control form-control-sm " id="isWorkFollow" name="IsWorkFollow" placeholder="IsWorkFollow">

                <input type="text" class="form-control form-control-sm " id="displayOn" name="DisplayOn" placeholder="DisplayOn">

                <input type="text" class="form-control form-control-sm " id="userId" name="UserId" placeholder="UserId">

                <input type="number" class="form-control form-control-sm " id="recordType" name="RecordType" placeholder="RecordType">


            </div>
        </div>
    </form>
    <input type="submit" value="Submit" class="form-control form-control-sm btn btn-success" onclick="formSubmit()" />
    @*public string Get_Dynamic_Grid_View(long ModuleId, long TableId, string FkId, string FilterExpression, string WorkfollowAction,
        int IsDeleteShow, int IsWorkFollow, string DisplayOn, string UserId, int RecordType)*@

</div>

<br />
<br />
<div class="row ml-1 border bg-white p-2" id="SQLResult">


</div>
<br />

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    function formSubmit() {
        var form = $("#myForm").serialize();
        //alert(form);
        $.ajax({
            type: "POST",
            url: '@Url.Action("Get_Dynamic_Grid_View", "GetDynamicTableInfo")',
            data: form,
            success: function (response) {
                console.log(response[0]);
                $("#SQLResult").html("<h2>" + response[0] + "</h2><p class='p-1'>" + response[1] + "</p><h2>" + response[2] + "</h2>");
            }
        });
    };

</script>

EnterpriceResourcePlaning(ERP)/Views/JsonDataGenerate/JsonfileRead - Copy.cshtml
@{
    ViewBag.Title = "JsonfileRead";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>JsonfileRead</h2>


<h3>Utl_Dynamic_Module Table</h3>
<table class="table table-bordered table-sm table-hover">
    <tr>
        <th>moduleId</th>
        <th>applicationId</th>
        <th>ExiModulId</th>
        <th>isNewCopy</th>
        <th>moduleName</th>
        <th>moduleCaption</th>
        <th>reportTitle</th>
        <th>isDrillDownReport</th>
        <th>categoryId</th>
        <th>imagePath</th>
        <th>moduleType</th>
        <th>siNo</th>
        <th>isActive</th>
        <th>developerSyId</th>
        <th>rowId</th>
        @*<th>entryUserId</th>
        <th>entryBy</th>
        <th>entryDate</th>
        <th>updateBy</th>
        <th>updateDate</th>
        <th>checkBy</th>
        <th>checkDate</th>
        <th>approveBy</th>
        <th>approveDate</th>
        <th>deleteBy</th>
        <th>deleteDate</th>
        <th>cancelBy</th>
        <th>cancelDate</th>
        <th>isApproved</th>
        <th>is_Active</th>
        <th>isDelete</th>
        <th>isCandel</th>
        <th>workFollowPosition</th>*@
    </tr>

    @foreach (var item in ViewBag.moduleData)
    {
        <tr>
            <td>@item.ModuleId</td>
            <td>@item.ApplicationId</td>
            <td>@item.ExistingModuleId</td>
            <td>@item.IsNewCopy</td>
            <td>@item.ModuleName</td>
            <td>@item.ModuleCaption</td>
            <td>@item.ReportTitle</td>
            <td>@item.IsDrilldownReport</td>
            <td>@item.CategoryId</td>
            <td>@item.ImagePath</td>
            <td>@item.ModuleType</td>

            <td>@item.SlNo</td>
            <td>@item.IsActive</td>
            <td>@item.DeveloperSyncId</td>
            <td>@item.Row_Id</td>
            @*<td>@item.Entry_User_Id</td>
            <td>@item.Entry_By</td>
            <td>@item.Entry_Date</td>
            <td>@item.Update_By</td>

            <td>@item.Update_Date</td>
            <td>@item.Check_By</td>
            <td>@item.Check_Date</td>
            <td>@item.Approve_By</td>
            <td>@item.Approve_Date</td>

            <td>@item.Delete_By</td>
            <td>@item.Delete_Date</td>
            <td>@item.Cancel_By</td>
            <td>@item.Cancel_Date</td>
            <td>@item.Is_Approved</td>
            <td>@item.Is_Active</td>
            <td>@item.Is_Deleted</td>
            <td>@item.Is_Cancel</td>
            <td>@item.Work_Follow_Position</td>*@

        </tr>
    }
</table>

EnterpriceResourcePlaning(ERP)/Views/JsonDataGenerate/JsonfileRead.cshtml
@{
    ViewBag.Title = "JsonfileRead";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>JsonfileRead</h2>


<h3>Utl_Dynamic_Module Table</h3>
<table class="table table-bordered table-sm table-hover">
    <tr>
        <th>moduleId</th>
        <th>applicationId</th>
        <th>ExiModulId</th>
        <th>isNewCopy</th>
        <th>moduleName</th>
        <th>moduleCaption</th>
        <th>reportTitle</th>
        <th>isDrillDownReport</th>
        <th>categoryId</th>
        <th>imagePath</th>
        <th>moduleType</th>
        <th>siNo</th>
        <th>isActive</th>
        <th>developerSyId</th>
        <th>rowId</th>
        @*<th>entryUserId</th>
        <th>entryBy</th>
        <th>entryDate</th>
        <th>updateBy</th>
        <th>updateDate</th>
        <th>checkBy</th>
        <th>checkDate</th>
        <th>approveBy</th>
        <th>approveDate</th>
        <th>deleteBy</th>
        <th>deleteDate</th>
        <th>cancelBy</th>
        <th>cancelDate</th>
        <th>isApproved</th>
        <th>is_Active</th>
        <th>isDelete</th>
        <th>isCandel</th>
        <th>workFollowPosition</th>*@
    </tr>

    @foreach (var item in ViewBag.moduleData)
    {
        <tr>
            <td>@item.ModuleId</td>
            <td>@item.ApplicationId</td>
            <td>@item.ExistingModuleId</td>
            <td>@item.IsNewCopy</td>
            <td>@item.ModuleName</td>
            <td>@item.ModuleCaption</td>
            <td>@item.ReportTitle</td>
            <td>@item.IsDrilldownReport</td>
            <td>@item.CategoryId</td>
            <td>@item.ImagePath</td>
            <td>@item.ModuleType</td>

            <td>@item.SlNo</td>
            <td>@item.IsActive</td>
            <td>@item.DeveloperSyncId</td>
            <td>@item.Row_Id</td>
            @*<td>@item.Entry_User_Id</td>
            <td>@item.Entry_By</td>
            <td>@item.Entry_Date</td>
            <td>@item.Update_By</td>

            <td>@item.Update_Date</td>
            <td>@item.Check_By</td>
            <td>@item.Check_Date</td>
            <td>@item.Approve_By</td>
            <td>@item.Approve_Date</td>

            <td>@item.Delete_By</td>
            <td>@item.Delete_Date</td>
            <td>@item.Cancel_By</td>
            <td>@item.Cancel_Date</td>
            <td>@item.Is_Approved</td>
            <td>@item.Is_Active</td>
            <td>@item.Is_Deleted</td>
            <td>@item.Is_Cancel</td>
            <td>@item.Work_Follow_Position</td>*@

        </tr>
    }
</table>